apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
  spec:
    containers:
      - name: customer-service
        image:  gcr.io/kubernetes-01-basic/customer-service:1.0
        ports:
          - containerPort: 3000
        env:
          - name: CUSTOMER_SVC_PORT
            value: "3000"
          - name: CUSTOMER_DB_URL
            value: "mongodb://mongo:27017/customer-db"
        imagePullPolicy: Always


